type:
  user: userDB
  product: productDB

userDB:
  host: user-db-host
  database: user-db
  user: user
  pass: passwd

productDB:
  host: product-db-host
  database: product-db
  user: user
  pass: passwd

service:
  host: your_host_url
  path: /path/to/your/server/where/events/will/be/processed
